version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5002:5002"
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "3002:3002"
    depends_on:
      - backend
    environment:
      - NODE_ENV=development