services:
  nswe-backend:
    build: ./backend
    container_name: nswe-backend
    expose:
      - 5002
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - default

  nswe-frontend:
    build: ./frontend
    container_name: nswe-frontend
    expose:
      - 3000
    env_file:
      - ./frontend/.env
    depends_on:
      - nswe-backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - nginxproxymanager_default
      - default

networks:
  nginxproxymanager_default:
    external: true
  default:
    driver: bridge
    name: nswe_net
