services:
  nswe-backend:
    build: ./backend
    container_name: nswe-backend
    expose:
      - 5000
    volumes:
      - ./data:/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - internal

  nswe-frontend:
    build: ./frontend
    container_name: nswe-frontend
    expose:
      - 3000
    env_file:
      - ./frontend/.env
    depends_on:
      - nswe-backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - internal
      - nginxproxymanager_default

  nswe-nginx-proxy:
    image: nginx:latest
    container_name: nswe-nginx-proxy
    ports:
      - 3000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nswe-frontend
    networks:
      - internal
      - nginxproxymanager_default

networks:
  nginxproxymanager_default:
    external: true
  internal:
    driver: bridge
    name: nswe_net
